name = "HelloMain"
uuid = "841a109e-f462-44fd-9fa1-197d115af013"
authors = ["tan <tanmaykm@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
julia = "1"
HTTP = "0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
